// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object TdlibBridgePigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Mirrors the subset of TdApi.AuthorizationState this module surfaces to Dart
 * (see app.sushi.tdlibbridge.auth.TdlibAuthState on the Kotlin side).
 */
enum class SushiTdlibAuthStateKind(val raw: Int) {
  UNINITIALIZED(0),
  WAITING_FOR_PHONE_NUMBER(1),
  WAITING_FOR_CODE(2),
  WAITING_FOR_PASSWORD(3),
  WAITING_FOR_QR_CONFIRMATION(4),
  READY(5),
  LOGGING_OUT(6),
  CLOSED(7),
  FAILED(8);

  companion object {
    fun ofRaw(raw: Int): SushiTdlibAuthStateKind? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Liveness of the MTProto socket — deliberately a different question from [SushiTdlibAuthStateKind].
 *
 * A device can hold perfectly valid credentials (auth `ready`) while its connection is dead, in
 * which case every byte fetch fails. Treating that as "logged out" is what sent TV users to a
 * login screen for something a silent reconnect fixes, so the two states are reported separately
 * and only [SushiTdlibAuthStateKind.failed] may ever drive a re-login prompt.
 */
enum class SushiTdlibConnectionHealth(val raw: Int) {
  /** configure() has not completed successfully yet. */
  UNINITIALIZED(0),
  /** A connection attempt (first connect, or a reconnect) is in flight. */
  CONNECTING(1),
  /** Socket is live; RPCs and playback downloads can be issued. */
  READY(2),
  /**
   * Socket died while credentials remain valid. The native side is already retrying with
   * backoff — surface it as a transient banner at most, never as a login prompt.
   */
  DEGRADED(3);

  companion object {
    fun ofRaw(raw: Int): SushiTdlibConnectionHealth? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SushiTdlibAuthState (
  val kind: SushiTdlibAuthStateKind,
  val qrLoginUrl: String? = null,
  val passwordHint: String? = null,
  val errorMessage: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SushiTdlibAuthState {
      val kind = pigeonVar_list[0] as SushiTdlibAuthStateKind
      val qrLoginUrl = pigeonVar_list[1] as String?
      val passwordHint = pigeonVar_list[2] as String?
      val errorMessage = pigeonVar_list[3] as String?
      return SushiTdlibAuthState(kind, qrLoginUrl, passwordHint, errorMessage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      kind,
      qrLoginUrl,
      passwordHint,
      errorMessage,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SushiTdlibAuthState) {
      return false
    }
    if (this === other) {
      return true
    }
    return TdlibBridgePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * One playback session's Telegram-backed video source, parsed from the PlaybackInfo Path
 * `sushi-tg://{providerBotId}/{messageId}?loc={locator}`.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class SushiTdlibPlaybackSource (
  /**
   * The delivery bot whose DM holds the video. 0 on a cold play: the backend round-robins across
   * senders and may fail over mid-request, so it does not commit to one until the copy lands —
   * the native side then learns the real sender from the update that carries [locator].
   */
  val providerBotId: Long,
  /**
   * The message id inside that DM, or 0 when the backend has none remembered yet and a fresh copy
   * is on its way (the native side then matches the live push by [locator] instead).
   */
  val messageId: Long,
  /**
   * True when the target player is mpv/mdk (no DataSource-style hook for a custom scheme) —
   * returns a http://127.0.0.1:{port}/{fileId} url served by TdlibHttpBridgeServer instead of
   * tdlib-file://{fileId}. False (default) keeps the existing ExoPlayer DataSource path.
   */
  val preferHttpBridge: Boolean,
  /**
   * The ?loc= query param off the PlaybackInfo Path: the caption on the copied message,
   * OXM_PREFIX_recordNo with no '#' (see apps/api's resolveTelegramDelivery). Unique per stored
   * file, and it does two jobs: it picks out the live-pushed document that answers THIS request
   * instead of whatever arrives next on the shared receive channel (confirmed a real bug without
   * it — concurrent dashboard-slider prefetches could hand one item's video to a different item's
   * player), and on the remembered path it verifies [messageId] still holds the expected file.
   * Always present now — both login modes read out of a DM.
   */
  val locator: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SushiTdlibPlaybackSource {
      val providerBotId = pigeonVar_list[0] as Long
      val messageId = pigeonVar_list[1] as Long
      val preferHttpBridge = pigeonVar_list[2] as Boolean
      val locator = pigeonVar_list[3] as String
      return SushiTdlibPlaybackSource(providerBotId, messageId, preferHttpBridge, locator)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      providerBotId,
      messageId,
      preferHttpBridge,
      locator,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SushiTdlibPlaybackSource) {
      return false
    }
    if (this === other) {
      return true
    }
    return TdlibBridgePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * One delivery sender, as published by the backend's GET /telegram/provider-bots. The username is
 * needed only for first contact (contacts.resolveUsername -> startBot); afterwards everything
 * addresses the bot by [id]. Tokens never reach the client.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class SushiTdlibProviderBot (
  val id: Long,
  val username: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SushiTdlibProviderBot {
      val id = pigeonVar_list[0] as Long
      val username = pigeonVar_list[1] as String
      return SushiTdlibProviderBot(id, username)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      username,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SushiTdlibProviderBot) {
      return false
    }
    if (this === other) {
      return true
    }
    return TdlibBridgePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Where a delivered video actually landed, as observed by THIS session. Both halves can only come
 * from the receiving side: private-chat message ids are numbered per side, and the server
 * round-robins across senders so it does not know which one won.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class SushiTdlibDeliveryRef (
  val messageId: Long,
  val providerBotId: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SushiTdlibDeliveryRef {
      val messageId = pigeonVar_list[0] as Long
      val providerBotId = pigeonVar_list[1] as Long
      return SushiTdlibDeliveryRef(messageId, providerBotId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      messageId,
      providerBotId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SushiTdlibDeliveryRef) {
      return false
    }
    if (this === other) {
      return true
    }
    return TdlibBridgePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class TdlibBridgePigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          SushiTdlibAuthStateKind.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          SushiTdlibConnectionHealth.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SushiTdlibAuthState.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SushiTdlibPlaybackSource.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SushiTdlibProviderBot.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SushiTdlibDeliveryRef.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is SushiTdlibAuthStateKind -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is SushiTdlibConnectionHealth -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is SushiTdlibAuthState -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is SushiTdlibPlaybackSource -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is SushiTdlibProviderBot -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is SushiTdlibDeliveryRef -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface SushiTdlibBridgeApi {
  /**
   * Must be called once before any other method (idempotent) — starts the underlying
   * TDLib client with [apiId]/[apiHash] from SushiEnv (this module's own user-session
   * credentials, distinct from the bot-based OX login's credentials).
   */
  fun configure(apiId: Long, apiHash: String, callback: (Result<Unit>) -> Unit)
  /**
   * Current auth state; also pushed via SushiTdlibBridgeEvents.onAuthStateChanged.
   * Synchronous — this just reads cached state, no TDLib round-trip.
   */
  fun currentAuthState(): SushiTdlibAuthState
  /**
   * Whether the CURRENT session — including one restored from disk at configure(), which never
   * calls submitBotToken this process — is a bot rather than a phone/QR user account.
   *
   * Ground truth from the native side, not derived client-side: the Dart bridge controller used
   * to infer this purely from whether IT had called submitBotToken during this run, which is
   * wrong the moment a previously-connected bot session is silently restored on a warm app start
   * (the normal case on every launch after the first). That made a reader-sync mismatch check
   * (backend now delivering to the account's linked Telegram session, native still holding a
   * stale restored bot session) never fire, and playback hung waiting on a push that could never
   * reach that bot's own inbox. Synchronous — an in-memory read on the Go side.
   */
  fun isNativeSessionBot(): Boolean
  /**
   * Current socket liveness; also pushed via SushiTdlibBridgeEvents.onConnectionHealthChanged.
   * Synchronous — an in-memory read on the Go side, no round-trip.
   */
  fun connectionHealth(): SushiTdlibConnectionHealth
  /**
   * Rebuilds the connection if its run loop has died; a no-op when already healthy.
   *
   * The native side reconnects on its own with backoff, so this is only for the moments where
   * waiting beats failing: app resume, and immediately before a playback download. Completes when
   * the connection is usable, or fails if it could not be re-established.
   */
  fun reconnect(callback: (Result<Unit>) -> Unit)
  /**
   * Kills and relaunches the whole app process (Android only).
   *
   * A stuck/failed native TDLib client can land in a state a plain in-memory reconfigure cannot
   * clear: go/oxtelegram/client.go's Configure() no-ops on "already have a live client object",
   * even one whose auth landed in `failed` — only a client object that never existed rebuilds
   * cleanly from the on-disk session. Killing the process is the only way to guarantee that from
   * here, since there is no "drop this client but keep the session file" call exposed yet (see
   * sushi_login_screen.dart's stuck-state UI). Session storage on disk is untouched, so the
   * relaunched process resumes the same signed-in session — this is not a logout.
   *
   * Never returns (the process exits); the return type exists only so Dart can await the call
   * being dispatched before the platform channel itself goes away.
   */
  fun restartApp(callback: (Result<Unit>) -> Unit)
  /** Phone/tablet flow, step 1. Async: waits on the real TdApi round-trip. */
  fun submitPhoneNumber(phoneNumber: String, callback: (Result<Unit>) -> Unit)
  /** Phone/tablet flow, step 2. */
  fun submitCode(code: String, callback: (Result<Unit>) -> Unit)
  /** Phone/tablet flow, step 3 — only valid when state is waitingForPassword. */
  fun submitTwoFactorPassword(password: String, callback: (Result<Unit>) -> Unit)
  /**
   * Android TV flow: request a QR login token; UI renders the URL pushed via
   * onAuthStateChanged(waitingForQrConfirmation) as a QR code.
   */
  fun requestQrLogin(callback: (Result<Unit>) -> Unit)
  /**
   * Bot-token login: an alternative to phone/QR for users who don't want to give Sushi
   * access to their personal Telegram account. Logs in as a bot (gotd/td
   * auth.importBotAuthorization) instead — goes straight to ready, no code/2FA step.
   */
  fun submitBotToken(token: String, callback: (Result<Unit>) -> Unit)
  /** Server-side session invalidation + local TDLib session wipe. */
  fun logOut(callback: (Result<Unit>) -> Unit)
  /**
   * Resolves [source] and starts downloading via TDLib, returning either a
   * tdlib-file://{fileId} uri (ExoPlayer DataSource path) or, when
   * source.preferHttpBridge is true, a http://127.0.0.1:{port}/{fileId} uri served by
   * TdlibHttpBridgeServer (mpv/mdk path — see that class for why).
   * Throws if no MTProto/TDLib session is logged in yet — callers should
   * check currentAuthState() first and prompt login if not ready.
   */
  fun startPlaybackSession(source: SushiTdlibPlaybackSource, callback: (Result<String>) -> Unit)
  /**
   * Where the last successful resolve of [locator] landed, or null if this session has not read
   * one. Dart reports it to the backend (POST /me/telegram-delivery) so the NEXT play of the same
   * file is answered straight from the delivery table with no Telegram copy at all.
   *
   * It has to come from here rather than from the server: copyMessage hands the SENDING bot an id
   * from its own side of the private chat, and private-chat ids are numbered per side, so only
   * the receiving session ever sees the id that can be re-read later — and only it knows which
   * sender the backend's round-robin actually settled on.
   * Synchronous — reads an in-memory map, no MTProto round-trip.
   */
  fun deliveryRefForLocator(locator: String): SushiTdlibDeliveryRef?
  /**
   * Registers interest in [locator] BEFORE the PlaybackInfo call that triggers the copy, so a
   * delivery that lands while that HTTP request is still in flight is captured rather than raced
   * for. Idempotent, synchronous, no MTProto round-trip.
   */
  fun armDeliveryWaiter(locator: String)
  /**
   * Resolves [source] and remembers where it landed WITHOUT opening a download — the warm-up path.
   * Scrolling the dashboard warms a dozen titles at once, and starting a dozen progressive
   * downloads for videos nobody pressed play on would spend the user's data on bytes that get
   * thrown away. Resolving is enough: it makes the backend remember the message id, so the
   * eventual play needs no Telegram call at all.
   */
  fun warmDelivery(source: SushiTdlibPlaybackSource, callback: (Result<Unit>) -> Unit)
  /**
   * Starts, mutes and archives every delivery sender on this account, so delivery copies never
   * land in the user's visible inbox. Called on every app enter (not just after login) because a
   * sender can be added to the backend's list at any time.
   *
   * No-op for a bot-token login: a bot is not a user account, has no dialog list to archive, and
   * its B2B DM was already opened by main-bot's /connectbot.
   */
  fun ensureProviderBotsReady(bots: List<SushiTdlibProviderBot>, callback: (Result<Unit>) -> Unit)
  /**
   * Stops the active playback session's download and closes the TDLib client (does not log
   * out — the on-disk session persists, next play just reconnects). Callers on every backend
   * (ExoPlayer's own hook is native-side via VideoPlayerImplementation.clearSession; mpv/mdk
   * have no equivalent Activity-scoped teardown, so their wrapper must call this explicitly
   * when a Telegram-sourced item finishes) — see TdlibBridgeObject.onTelegramPlaybackEnded.
   */
  fun stopPlaybackSession(sessionUri: String, callback: (Result<Unit>) -> Unit)
  /**
   * Fetches a Telegram-signed Mini App `initData` payload for [botUsername] via TDLib's
   * GetWebAppLinkUrl/GetWebAppUrl/GetMainWebApp — requires a Ready auth state (real Telegram
   * login already completed) and a Mini App configured on that bot via @BotFather. Exchange the
   * result with the backend's POST /auth/telegram to obtain OX session tokens; see
   * SushiTelegramAuthClient. [webAppShortName]/[hostedHttpsUrl] may be null/empty if unset —
   * at least one working WebApp path must be configured on the bot for this to succeed.
   */
  fun fetchWebAppInitData(botUsername: String, webAppShortName: String?, hostedHttpsUrl: String?, callback: (Result<String>) -> Unit)
  /**
   * DMs [username] with [text] and waits for the next private-chat reply starting with `!`
   * (Sushi wire framing). Used for `/initbot <corr>` against init-bot. [timeoutMs] ≤ 0 → 30000.
   */
  fun sendTextAndWaitReply(username: String, text: String, timeoutMs: Long, callback: (Result<String>) -> Unit)
  /**
   * DMs [username] with [text] without waiting for a reply — the fire-and-forget half of the
   * wire protocol, for a Sushi command whose reply the client does not read (`/ack`; a future
   * best-effort watch-progress report). Returns once the message is sent; unlike
   * [sendTextAndWaitReply] it never blocks on a server reply, so it cannot stall the caller
   * waiting on one that is never coming.
   */
  fun sendTextFireAndForget(username: String, text: String, callback: (Result<Unit>) -> Unit)
  /**
   * Clicks a session account through main-bot's onboarding conversation (language, quality,
   * audio, then login) by pressing the first inline button offered at each step, so `/initbot`
   * has a binding to read afterward without a human tapping through Telegram by hand. No-op for
   * a bot-token login (no dialog list, no onboarding conversation to have). [timeoutMs] bounds
   * the whole multi-step conversation, not one round trip; ≤ 0 → 90000.
   */
  fun ensureMainBotOnboarded(username: String, timeoutMs: Long, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by SushiTdlibBridgeApi. */
    val codec: MessageCodec<Any?> by lazy {
      TdlibBridgePigeonCodec()
    }
    /** Sets up an instance of `SushiTdlibBridgeApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: SushiTdlibBridgeApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.SushiTdlibBridgeApi.configure$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val apiIdArg = args[0] as Long
            val apiHashArg = args[1] as String
            api.configure(apiIdArg, apiHashArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TdlibBridgePigeonUtils.wrapError(error))
              } else {
                reply.reply(TdlibBridgePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.SushiTdlibBridgeApi.currentAuthState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.currentAuthState())
            } catch (exception: Throwable) {
              TdlibBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.SushiTdlibBridgeApi.isNativeSessionBot$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isNativeSessionBot())
            } catch (exception: Throwable) {
              TdlibBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.SushiTdlibBridgeApi.connectionHealth$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.connectionHealth())
            } catch (exception: Throwable) {
              TdlibBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.SushiTdlibBridgeApi.reconnect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.reconnect{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TdlibBridgePigeonUtils.wrapError(error))
              } else {
                reply.reply(TdlibBridgePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.SushiTdlibBridgeApi.restartApp$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.restartApp{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TdlibBridgePigeonUtils.wrapError(error))
              } else {
                reply.reply(TdlibBridgePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.SushiTdlibBridgeApi.submitPhoneNumber$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val phoneNumberArg = args[0] as String
            api.submitPhoneNumber(phoneNumberArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TdlibBridgePigeonUtils.wrapError(error))
              } else {
                reply.reply(TdlibBridgePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.SushiTdlibBridgeApi.submitCode$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val codeArg = args[0] as String
            api.submitCode(codeArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TdlibBridgePigeonUtils.wrapError(error))
              } else {
                reply.reply(TdlibBridgePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.SushiTdlibBridgeApi.submitTwoFactorPassword$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val passwordArg = args[0] as String
            api.submitTwoFactorPassword(passwordArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TdlibBridgePigeonUtils.wrapError(error))
              } else {
                reply.reply(TdlibBridgePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.SushiTdlibBridgeApi.requestQrLogin$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.requestQrLogin{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TdlibBridgePigeonUtils.wrapError(error))
              } else {
                reply.reply(TdlibBridgePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.SushiTdlibBridgeApi.submitBotToken$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val tokenArg = args[0] as String
            api.submitBotToken(tokenArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TdlibBridgePigeonUtils.wrapError(error))
              } else {
                reply.reply(TdlibBridgePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.SushiTdlibBridgeApi.logOut$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.logOut{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TdlibBridgePigeonUtils.wrapError(error))
              } else {
                reply.reply(TdlibBridgePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.SushiTdlibBridgeApi.startPlaybackSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sourceArg = args[0] as SushiTdlibPlaybackSource
            api.startPlaybackSession(sourceArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TdlibBridgePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(TdlibBridgePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.SushiTdlibBridgeApi.deliveryRefForLocator$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val locatorArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.deliveryRefForLocator(locatorArg))
            } catch (exception: Throwable) {
              TdlibBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.SushiTdlibBridgeApi.armDeliveryWaiter$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val locatorArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.armDeliveryWaiter(locatorArg)
              listOf(null)
            } catch (exception: Throwable) {
              TdlibBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.SushiTdlibBridgeApi.warmDelivery$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sourceArg = args[0] as SushiTdlibPlaybackSource
            api.warmDelivery(sourceArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TdlibBridgePigeonUtils.wrapError(error))
              } else {
                reply.reply(TdlibBridgePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.SushiTdlibBridgeApi.ensureProviderBotsReady$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val botsArg = args[0] as List<SushiTdlibProviderBot>
            api.ensureProviderBotsReady(botsArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TdlibBridgePigeonUtils.wrapError(error))
              } else {
                reply.reply(TdlibBridgePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.SushiTdlibBridgeApi.stopPlaybackSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionUriArg = args[0] as String
            api.stopPlaybackSession(sessionUriArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TdlibBridgePigeonUtils.wrapError(error))
              } else {
                reply.reply(TdlibBridgePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.SushiTdlibBridgeApi.fetchWebAppInitData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val botUsernameArg = args[0] as String
            val webAppShortNameArg = args[1] as String?
            val hostedHttpsUrlArg = args[2] as String?
            api.fetchWebAppInitData(botUsernameArg, webAppShortNameArg, hostedHttpsUrlArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TdlibBridgePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(TdlibBridgePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.SushiTdlibBridgeApi.sendTextAndWaitReply$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val usernameArg = args[0] as String
            val textArg = args[1] as String
            val timeoutMsArg = args[2] as Long
            api.sendTextAndWaitReply(usernameArg, textArg, timeoutMsArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TdlibBridgePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(TdlibBridgePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.SushiTdlibBridgeApi.sendTextFireAndForget$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val usernameArg = args[0] as String
            val textArg = args[1] as String
            api.sendTextFireAndForget(usernameArg, textArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TdlibBridgePigeonUtils.wrapError(error))
              } else {
                reply.reply(TdlibBridgePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.SushiTdlibBridgeApi.ensureMainBotOnboarded$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val usernameArg = args[0] as String
            val timeoutMsArg = args[1] as Long
            api.ensureMainBotOnboarded(usernameArg, timeoutMsArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TdlibBridgePigeonUtils.wrapError(error))
              } else {
                reply.reply(TdlibBridgePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class SushiTdlibBridgeEvents(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by SushiTdlibBridgeEvents. */
    val codec: MessageCodec<Any?> by lazy {
      TdlibBridgePigeonCodec()
    }
  }
  fun onAuthStateChanged(stateArg: SushiTdlibAuthState, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.SushiTdlibBridgeEvents.onAuthStateChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(stateArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(TdlibBridgePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  /**
   * Pushed whenever socket liveness changes. Independent of onAuthStateChanged — see
   * [SushiTdlibConnectionHealth] for why the two must not be collapsed into one signal.
   */
  fun onConnectionHealthChanged(healthArg: SushiTdlibConnectionHealth, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.SushiTdlibBridgeEvents.onConnectionHealthChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(healthArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(TdlibBridgePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
