// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


/// Mirrors the subset of TdApi.AuthorizationState this module surfaces to Dart
/// (see app.oxplayer.tdlibbridge.auth.TdlibAuthState on the Kotlin side).
enum OxTdlibAuthStateKind {
  uninitialized,
  waitingForPhoneNumber,
  waitingForCode,
  waitingForPassword,
  waitingForQrConfirmation,
  ready,
  loggingOut,
  closed,
  failed,
}

/// Liveness of the MTProto socket — deliberately a different question from [OxTdlibAuthStateKind].
///
/// A device can hold perfectly valid credentials (auth `ready`) while its connection is dead, in
/// which case every byte fetch fails. Treating that as "logged out" is what sent TV users to a
/// login screen for something a silent reconnect fixes, so the two states are reported separately
/// and only [OxTdlibAuthStateKind.failed] may ever drive a re-login prompt.
enum OxTdlibConnectionHealth {
  /// configure() has not completed successfully yet.
  uninitialized,
  /// A connection attempt (first connect, or a reconnect) is in flight.
  connecting,
  /// Socket is live; RPCs and playback downloads can be issued.
  ready,
  /// Socket died while credentials remain valid. The native side is already retrying with
  /// backoff — surface it as a transient banner at most, never as a login prompt.
  degraded,
}

class OxTdlibAuthState {
  OxTdlibAuthState({
    required this.kind,
    this.qrLoginUrl,
    this.passwordHint,
    this.errorMessage,
  });

  OxTdlibAuthStateKind kind;

  String? qrLoginUrl;

  String? passwordHint;

  String? errorMessage;

  List<Object?> _toList() {
    return <Object?>[
      kind,
      qrLoginUrl,
      passwordHint,
      errorMessage,
    ];
  }

  Object encode() {
    return _toList();  }

  static OxTdlibAuthState decode(Object result) {
    result as List<Object?>;
    return OxTdlibAuthState(
      kind: result[0]! as OxTdlibAuthStateKind,
      qrLoginUrl: result[1] as String?,
      passwordHint: result[2] as String?,
      errorMessage: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OxTdlibAuthState || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// One playback session's Telegram-backed video source, parsed from the PlaybackInfo Path
/// `oxplayer-tg://{providerBotId}/{messageId}?loc={locator}`.
class OxTdlibPlaybackSource {
  OxTdlibPlaybackSource({
    required this.providerBotId,
    required this.messageId,
    required this.preferHttpBridge,
    required this.locator,
  });

  /// The delivery bot whose DM holds the video. 0 on a cold play: the backend round-robins across
  /// senders and may fail over mid-request, so it does not commit to one until the copy lands —
  /// the native side then learns the real sender from the update that carries [locator].
  int providerBotId;

  /// The message id inside that DM, or 0 when the backend has none remembered yet and a fresh copy
  /// is on its way (the native side then matches the live push by [locator] instead).
  int messageId;

  /// True when the target player is mpv/mdk (no DataSource-style hook for a custom scheme) —
  /// returns a http://127.0.0.1:{port}/{fileId} url served by TdlibHttpBridgeServer instead of
  /// tdlib-file://{fileId}. False (default) keeps the existing ExoPlayer DataSource path.
  bool preferHttpBridge;

  /// The ?loc= query param off the PlaybackInfo Path: the caption on the copied message,
  /// OXM_PREFIX_recordNo with no '#' (see apps/api's resolveTelegramDelivery). Unique per stored
  /// file, and it does two jobs: it picks out the live-pushed document that answers THIS request
  /// instead of whatever arrives next on the shared receive channel (confirmed a real bug without
  /// it — concurrent dashboard-slider prefetches could hand one item's video to a different item's
  /// player), and on the remembered path it verifies [messageId] still holds the expected file.
  /// Always present now — both login modes read out of a DM.
  String locator;

  List<Object?> _toList() {
    return <Object?>[
      providerBotId,
      messageId,
      preferHttpBridge,
      locator,
    ];
  }

  Object encode() {
    return _toList();  }

  static OxTdlibPlaybackSource decode(Object result) {
    result as List<Object?>;
    return OxTdlibPlaybackSource(
      providerBotId: result[0]! as int,
      messageId: result[1]! as int,
      preferHttpBridge: result[2]! as bool,
      locator: result[3]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OxTdlibPlaybackSource || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// One delivery sender, as published by the backend's GET /telegram/provider-bots. The username is
/// needed only for first contact (contacts.resolveUsername -> startBot); afterwards everything
/// addresses the bot by [id]. Tokens never reach the client.
class OxTdlibProviderBot {
  OxTdlibProviderBot({
    required this.id,
    required this.username,
  });

  int id;

  String username;

  List<Object?> _toList() {
    return <Object?>[
      id,
      username,
    ];
  }

  Object encode() {
    return _toList();  }

  static OxTdlibProviderBot decode(Object result) {
    result as List<Object?>;
    return OxTdlibProviderBot(
      id: result[0]! as int,
      username: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OxTdlibProviderBot || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Where a delivered video actually landed, as observed by THIS session. Both halves can only come
/// from the receiving side: private-chat message ids are numbered per side, and the server
/// round-robins across senders so it does not know which one won.
class OxTdlibDeliveryRef {
  OxTdlibDeliveryRef({
    required this.messageId,
    required this.providerBotId,
  });

  int messageId;

  int providerBotId;

  List<Object?> _toList() {
    return <Object?>[
      messageId,
      providerBotId,
    ];
  }

  Object encode() {
    return _toList();  }

  static OxTdlibDeliveryRef decode(Object result) {
    result as List<Object?>;
    return OxTdlibDeliveryRef(
      messageId: result[0]! as int,
      providerBotId: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OxTdlibDeliveryRef || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is OxTdlibAuthStateKind) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is OxTdlibConnectionHealth) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is OxTdlibAuthState) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is OxTdlibPlaybackSource) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is OxTdlibProviderBot) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is OxTdlibDeliveryRef) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : OxTdlibAuthStateKind.values[value];
      case 130: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : OxTdlibConnectionHealth.values[value];
      case 131: 
        return OxTdlibAuthState.decode(readValue(buffer)!);
      case 132: 
        return OxTdlibPlaybackSource.decode(readValue(buffer)!);
      case 133: 
        return OxTdlibProviderBot.decode(readValue(buffer)!);
      case 134: 
        return OxTdlibDeliveryRef.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class OxTdlibBridgeApi {
  /// Constructor for [OxTdlibBridgeApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  OxTdlibBridgeApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Must be called once before any other method (idempotent) — starts the underlying
  /// TDLib client with [apiId]/[apiHash] from OxplayerEnv (this module's own user-session
  /// credentials, distinct from the bot-based OX login's credentials).
  Future<void> configure(int apiId, String apiHash) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.OxTdlibBridgeApi.configure$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[apiId, apiHash]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Current auth state; also pushed via OxTdlibBridgeEvents.onAuthStateChanged.
  /// Synchronous — this just reads cached state, no TDLib round-trip.
  Future<OxTdlibAuthState> currentAuthState() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.OxTdlibBridgeApi.currentAuthState$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as OxTdlibAuthState?)!;
    }
  }

  /// Whether the CURRENT session — including one restored from disk at configure(), which never
  /// calls submitBotToken this process — is a bot rather than a phone/QR user account.
  ///
  /// Ground truth from the native side, not derived client-side: the Dart bridge controller used
  /// to infer this purely from whether IT had called submitBotToken during this run, which is
  /// wrong the moment a previously-connected bot session is silently restored on a warm app start
  /// (the normal case on every launch after the first). That made a reader-sync mismatch check
  /// (backend now delivering to the account's linked Telegram session, native still holding a
  /// stale restored bot session) never fire, and playback hung waiting on a push that could never
  /// reach that bot's own inbox. Synchronous — an in-memory read on the Go side.
  Future<bool> isNativeSessionBot() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.OxTdlibBridgeApi.isNativeSessionBot$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Current socket liveness; also pushed via OxTdlibBridgeEvents.onConnectionHealthChanged.
  /// Synchronous — an in-memory read on the Go side, no round-trip.
  Future<OxTdlibConnectionHealth> connectionHealth() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.OxTdlibBridgeApi.connectionHealth$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as OxTdlibConnectionHealth?)!;
    }
  }

  /// Rebuilds the connection if its run loop has died; a no-op when already healthy.
  ///
  /// The native side reconnects on its own with backoff, so this is only for the moments where
  /// waiting beats failing: app resume, and immediately before a playback download. Completes when
  /// the connection is usable, or fails if it could not be re-established.
  Future<void> reconnect() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.OxTdlibBridgeApi.reconnect$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Kills and relaunches the whole app process (Android only).
  ///
  /// A stuck/failed native TDLib client can land in a state a plain in-memory reconfigure cannot
  /// clear: go/oxtelegram/client.go's Configure() no-ops on "already have a live client object",
  /// even one whose auth landed in `failed` — only a client object that never existed rebuilds
  /// cleanly from the on-disk session. Killing the process is the only way to guarantee that from
  /// here, since there is no "drop this client but keep the session file" call exposed yet (see
  /// oxplayer_login_screen.dart's stuck-state UI). Session storage on disk is untouched, so the
  /// relaunched process resumes the same signed-in session — this is not a logout.
  ///
  /// Never returns (the process exits); the return type exists only so Dart can await the call
  /// being dispatched before the platform channel itself goes away.
  Future<void> restartApp() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.OxTdlibBridgeApi.restartApp$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Phone/tablet flow, step 1. Async: waits on the real TdApi round-trip.
  Future<void> submitPhoneNumber(String phoneNumber) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.OxTdlibBridgeApi.submitPhoneNumber$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[phoneNumber]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Phone/tablet flow, step 2.
  Future<void> submitCode(String code) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.OxTdlibBridgeApi.submitCode$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[code]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Phone/tablet flow, step 3 — only valid when state is waitingForPassword.
  Future<void> submitTwoFactorPassword(String password) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.OxTdlibBridgeApi.submitTwoFactorPassword$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[password]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Android TV flow: request a QR login token; UI renders the URL pushed via
  /// onAuthStateChanged(waitingForQrConfirmation) as a QR code.
  Future<void> requestQrLogin() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.OxTdlibBridgeApi.requestQrLogin$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Bot-token login: an alternative to phone/QR for users who don't want to give OXPlayer
  /// access to their personal Telegram account. Logs in as a bot (gotd/td
  /// auth.importBotAuthorization) instead — goes straight to ready, no code/2FA step.
  Future<void> submitBotToken(String token) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.OxTdlibBridgeApi.submitBotToken$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[token]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Server-side session invalidation + local TDLib session wipe.
  Future<void> logOut() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.OxTdlibBridgeApi.logOut$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Resolves [source] and starts downloading via TDLib, returning either a
  /// tdlib-file://{fileId} uri (ExoPlayer DataSource path) or, when
  /// source.preferHttpBridge is true, a http://127.0.0.1:{port}/{fileId} uri served by
  /// TdlibHttpBridgeServer (mpv/mdk path — see that class for why).
  /// Throws if no MTProto/TDLib session is logged in yet — callers should
  /// check currentAuthState() first and prompt login if not ready.
  Future<String> startPlaybackSession(OxTdlibPlaybackSource source) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.OxTdlibBridgeApi.startPlaybackSession$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[source]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  /// Where the last successful resolve of [locator] landed, or null if this session has not read
  /// one. Dart reports it to the backend (POST /me/telegram-delivery) so the NEXT play of the same
  /// file is answered straight from the delivery table with no Telegram copy at all.
  ///
  /// It has to come from here rather than from the server: copyMessage hands the SENDING bot an id
  /// from its own side of the private chat, and private-chat ids are numbered per side, so only
  /// the receiving session ever sees the id that can be re-read later — and only it knows which
  /// sender the backend's round-robin actually settled on.
  /// Synchronous — reads an in-memory map, no MTProto round-trip.
  Future<OxTdlibDeliveryRef?> deliveryRefForLocator(String locator) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.OxTdlibBridgeApi.deliveryRefForLocator$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[locator]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as OxTdlibDeliveryRef?);
    }
  }

  /// Registers interest in [locator] BEFORE the PlaybackInfo call that triggers the copy, so a
  /// delivery that lands while that HTTP request is still in flight is captured rather than raced
  /// for. Idempotent, synchronous, no MTProto round-trip.
  Future<void> armDeliveryWaiter(String locator) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.OxTdlibBridgeApi.armDeliveryWaiter$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[locator]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Resolves [source] and remembers where it landed WITHOUT opening a download — the warm-up path.
  /// Scrolling the dashboard warms a dozen titles at once, and starting a dozen progressive
  /// downloads for videos nobody pressed play on would spend the user's data on bytes that get
  /// thrown away. Resolving is enough: it makes the backend remember the message id, so the
  /// eventual play needs no Telegram call at all.
  Future<void> warmDelivery(OxTdlibPlaybackSource source) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.OxTdlibBridgeApi.warmDelivery$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[source]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Starts, mutes and archives every delivery sender on this account, so delivery copies never
  /// land in the user's visible inbox. Called on every app enter (not just after login) because a
  /// sender can be added to the backend's list at any time.
  ///
  /// No-op for a bot-token login: a bot is not a user account, has no dialog list to archive, and
  /// its B2B DM was already opened by main-bot's /connectbot.
  Future<void> ensureProviderBotsReady(List<OxTdlibProviderBot> bots) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.OxTdlibBridgeApi.ensureProviderBotsReady$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[bots]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Stops the active playback session's download and closes the TDLib client (does not log
  /// out — the on-disk session persists, next play just reconnects). Callers on every backend
  /// (ExoPlayer's own hook is native-side via VideoPlayerImplementation.clearSession; mpv/mdk
  /// have no equivalent Activity-scoped teardown, so their wrapper must call this explicitly
  /// when a Telegram-sourced item finishes) — see TdlibBridgeObject.onTelegramPlaybackEnded.
  Future<void> stopPlaybackSession(String sessionUri) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.OxTdlibBridgeApi.stopPlaybackSession$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionUri]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Fetches a Telegram-signed Mini App `initData` payload for [botUsername] via TDLib's
  /// GetWebAppLinkUrl/GetWebAppUrl/GetMainWebApp — requires a Ready auth state (real Telegram
  /// login already completed) and a Mini App configured on that bot via @BotFather. Exchange the
  /// result with the backend's POST /auth/telegram to obtain OX session tokens; see
  /// OxplayerTelegramAuthClient. [webAppShortName]/[hostedHttpsUrl] may be null/empty if unset —
  /// at least one working WebApp path must be configured on the bot for this to succeed.
  Future<String> fetchWebAppInitData(String botUsername, String? webAppShortName, String? hostedHttpsUrl) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.OxTdlibBridgeApi.fetchWebAppInitData$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[botUsername, webAppShortName, hostedHttpsUrl]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }
}

abstract class OxTdlibBridgeEvents {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onAuthStateChanged(OxTdlibAuthState state);

  /// Pushed whenever socket liveness changes. Independent of onAuthStateChanged — see
  /// [OxTdlibConnectionHealth] for why the two must not be collapsed into one signal.
  void onConnectionHealthChanged(OxTdlibConnectionHealth health);

  static void setUp(OxTdlibBridgeEvents? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.OxTdlibBridgeEvents.onAuthStateChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.OxTdlibBridgeEvents.onAuthStateChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final OxTdlibAuthState? arg_state = (args[0] as OxTdlibAuthState?);
          assert(arg_state != null,
              'Argument for dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.OxTdlibBridgeEvents.onAuthStateChanged was null, expected non-null OxTdlibAuthState.');
          try {
            api.onAuthStateChanged(arg_state!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.OxTdlibBridgeEvents.onConnectionHealthChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.OxTdlibBridgeEvents.onConnectionHealthChanged was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final OxTdlibConnectionHealth? arg_health = (args[0] as OxTdlibConnectionHealth?);
          assert(arg_health != null,
              'Argument for dev.flutter.pigeon.nl_jknaapen_fladder.tdlib_bridge.OxTdlibBridgeEvents.onConnectionHealthChanged was null, expected non-null OxTdlibConnectionHealth.');
          try {
            api.onConnectionHealthChanged(arg_health!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
